In [ ]:
import pandas as pd
# fund_data = pd.read_csv("fundamentals.csv")
# sec_data = pd.read_csv("securities.csv")
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test_template.csv")
train_groups = train_data.groupby('symbol')
test_groups = test_data.groupby('symbol')

,date,symbol,open,close,low,high,volume
0,2010-01-04,SYMC,18.040001,18.400000,18.010000,18.530001,8322300.0
1,2010-01-04,IFF,41.509998,42.009998,41.500000,42.020000,286000.0
2,2010-01-04,ILMN,31.120001,30.549999,30.420000,31.230000,1793700.0
3,2010-01-04,INTC,20.790001,20.879999,20.730000,21.030001,47800900.0
4,2010-01-04,INTU,31.090000,30.809999,30.770000,31.150000,2353000.0
...,...,...,...,...,...,...,...
680817,2015-08-25,CERN,61.919998,60.240002,60.189999,62.369999,3597300.0
680818,2015-08-25,CELG,118.639999,112.699997,112.660004,119.500000,8331600.0
680819,2015-08-25,CCL,48.419998,47.340000,47.320000,48.939999,7940600.0
680820,2015-08-25,CCI,81.330002,79.529999,79.500000,81.889999,3750600.0
680821,2015-08-25,CFG,23.799999,23.100000,23.070000,24.080000,5607800.0

In [10]:
train_groups.get_group('ILMN').head(10)  # 查看ILMN的前10行数据]]
# train_groups.get_group('ILMN').tail(10)  # 查看ILMN的后10行数据
# test_groups.get_group('ILMN').head(10)  # 查看ILMN的前10行数据

,date,symbol,open,close,low,high,volume
2,2010-01-04,ILMN,31.120001,30.549999,30.420000,31.230000,1793700.0
744,2010-01-05,ILMN,30.370001,30.350000,29.760000,30.500000,3039700.0
1206,2010-01-06,ILMN,30.240000,32.220001,30.240000,32.430000,4065700.0
1406,2010-01-07,ILMN,32.240002,32.770000,32.000000,33.209999,9060000.0
1871,2010-01-08,ILMN,32.599998,33.150002,32.080002,33.279999,2681600.0
2574,2010-01-11,ILMN,33.299999,33.820000,33.049999,34.029999,2215000.0
3050,2010-01-12,ILMN,33.730000,39.169998,33.090000,39.240002,16032000.0
3277,2010-01-13,ILMN,39.660000,40.509998,38.790001,40.900002,12337900.0
3986,2010-01-14,ILMN,40.150002,39.029999,38.439999,40.330002,3640600.0
4212,2010-01-15,ILMN,39.299999,39.020000,38.490002,39.930000,2911200.0